<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [26]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [27]:
%%sql
select
date_trunc('month',orderdate):: date as order_month,
sum(quantity*netprice*exchangerate) as net_revenue,
count(DISTINCT customerkey) as total_customers
from sales
group by
    order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue  total_customers
0    2015-01-01    384092.66              200
1    2015-02-01    706374.12              291
2    2015-03-01    332961.59              139
3    2015-04-01    160767.00               78
4    2015-05-01    548632.63              236
..          ...          ...              ...
107  2023-12-01   2928550.93             1484
108  2024-01-01   2677498.55             1340
109  2024-02-01   3542322.55             1718
110  2024-03-01   1692854.89              877
111  2024-04-01    483851.39              246

[112 rows x 3 columns]

In [28]:
%%sql
select orderdate,
to_char(orderdate,'yyyy')
from sales
order by random()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate to_char
0       2017-12-21    2017
1       2021-10-20    2021
2       2021-05-06    2021
3       2019-04-29    2019
4       2021-05-05    2021
...            ...     ...
199868  2021-05-26    2021
199869  2024-01-03    2024
199870  2022-08-10    2022
199871  2022-10-05    2022
199872  2019-09-30    2019

[199873 rows x 2 columns]

In [29]:
%%sql
select orderdate,
to_char(orderdate,'yyyy-mm')
from sales
order by random()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate  to_char
0       2022-11-12  2022-11
1       2023-11-08  2023-11
2       2022-08-05  2022-08
3       2023-05-24  2023-05
4       2015-06-15  2015-06
...            ...      ...
199868  2021-11-16  2021-11
199869  2022-05-08  2022-05
199870  2023-01-04  2023-01
199871  2019-09-25  2019-09
199872  2016-11-16  2016-11

[199873 rows x 2 columns]

In [30]:
%%sql
select orderdate,
date_part('year',orderdate) as order_year,
date_part('month',orderdate) as order_month,
date_part('day',orderdate) as order_day
from sales
order by random()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate  order_year  order_month  order_day
0       2022-09-09     2022.00         9.00       9.00
1       2018-08-17     2018.00         8.00      17.00
2       2022-05-20     2022.00         5.00      20.00
3       2023-02-18     2023.00         2.00      18.00
4       2022-09-22     2022.00         9.00      22.00
...            ...         ...          ...        ...
199868  2019-02-23     2019.00         2.00      23.00
199869  2018-06-20     2018.00         6.00      20.00
199870  2022-07-06     2022.00         7.00       6.00
199871  2024-01-11     2024.00         1.00      11.00
199872  2022-03-18     2022.00         3.00      18.00

[199873 rows x 4 columns]

In [31]:
%%sql
select orderdate,
EXTRACT('YEAR'FROM orderdate) as extract_year,
EXTRACT('MONTH'FROM orderdate) as extract_month,
EXTRACT('DAY'FROM orderdate) as extract_day
from sales
order by random()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate extract_year extract_month extract_day
0       2016-03-05         2016             3           5
1       2023-08-16         2023             8          16
2       2019-09-29         2019             9          29
3       2022-05-28         2022             5          28
4       2018-12-29         2018            12          29
...            ...          ...           ...         ...
199868  2016-08-24         2016             8          24
199869  2019-09-04         2019             9           4
199870  2021-12-15         2021            12          15
199871  2018-12-06         2018            12           6
199872  2022-05-10         2022             5          10

[199873 rows x 4 columns]

In [32]:
%%sql
select
to_char(orderdate,'yyyy-mm') AS order_month,
sum(quantity*netprice*exchangerate) as net_revenue,
extract(YEAR from orderdate) as extract_year,
extract(MONTH from orderdate) as extract_month
from sales
GROUP BY orderdate
order by random()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3294 rows affected.

     order_month  net_revenue extract_year extract_month
0        2019-07     83247.25         2019             7
1        2017-08     43108.94         2017             8
2        2016-06     47979.54         2016             6
3        2016-09     43695.33         2016             9
4        2021-04      2564.55         2021             4
...          ...          ...          ...           ...
3289     2015-07     16410.78         2015             7
3290     2018-08    138571.78         2018             8
3291     2023-10     74125.79         2023            10
3292     2021-09      7177.27         2021             9
3293     2023-06    112462.76         2023             6

[3294 rows x 4 columns]

In [33]:
%%sql
select

extract(YEAR from orderdate) as order_year,
extract(MONTH from orderdate) as order_month,
sum(quantity*netprice*exchangerate) as net_revenue
from sales
GROUP BY order_year,order_month
order by order_year,order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  net_revenue
0         2015           1    384092.66
1         2015           2    706374.12
2         2015           3    332961.59
3         2015           4    160767.00
4         2015           5    548632.63
..         ...         ...          ...
107       2023          12   2928550.93
108       2024           1   2677498.55
109       2024           2   3542322.55
110       2024           3   1692854.89
111       2024           4    483851.39

[112 rows x 3 columns]

In [34]:
%%sql
select current_date

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2025-08-24

In [35]:
%%sql
select now()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

                               now
0 2025-08-24 07:00:48.568272+00:00

In [36]:
%%sql

select current_date,orderdate,categoryname,
sum(exchangerate*netprice*quantity) as net_revenue
from sales s
join product p
on s.productkey=p.productkey
where orderdate between '2020-01-01' and '2024-12-31'
group by orderdate,categoryname
order by orderdate,categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

11171 rows affected.

      current_date   orderdate                   categoryname  net_revenue
0       2025-08-24  2020-01-01                          Audio      5490.14
1       2025-08-24  2020-01-01        Cameras and camcorders      18880.06
2       2025-08-24  2020-01-01                    Cell phones     22593.00
3       2025-08-24  2020-01-01                      Computers     78554.54
4       2025-08-24  2020-01-01                 Games and Toys      1476.43
...            ...         ...                            ...          ...
11166   2025-08-24  2024-04-20                      Computers     58353.68
11167   2025-08-24  2024-04-20                 Games and Toys      1744.30
11168   2025-08-24  2024-04-20                Home Appliances      1562.04
11169   2025-08-24  2024-04-20  Music, Movies and Audio Books      4949.43
11170   2025-08-24  2024-04-20                   TV and Video      9841.91

[11171 rows x 4 columns]

In [37]:
%%sql
select current_date,orderdate,
categoryname,
sum(exchangerate*netprice*quantity) as net_revenue
from sales s
join product p
on s.productkey=p.productkey
where extract(YEAR from orderdate) >= extract(YEAR from current_date) -5
group by orderdate,categoryname
order by orderdate,categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

11171 rows affected.

      current_date   orderdate                   categoryname  net_revenue
0       2025-08-24  2020-01-01                          Audio      5490.14
1       2025-08-24  2020-01-01        Cameras and camcorders      18880.06
2       2025-08-24  2020-01-01                    Cell phones     22593.00
3       2025-08-24  2020-01-01                      Computers     78554.54
4       2025-08-24  2020-01-01                 Games and Toys      1476.43
...            ...         ...                            ...          ...
11166   2025-08-24  2024-04-20                      Computers     58353.68
11167   2025-08-24  2024-04-20                 Games and Toys      1744.30
11168   2025-08-24  2024-04-20                Home Appliances      1562.04
11169   2025-08-24  2024-04-20  Music, Movies and Audio Books      4949.43
11170   2025-08-24  2024-04-20                   TV and Video      9841.91

[11171 rows x 4 columns]

In [38]:
%%sql
select  interval '5 centuries',interval '5 months'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

               interval interval
0  182500 days, 0:00:00 150 days

In [39]:
%%sql
select current_date,orderdate

from sales s
where
  orderdate>= current_date- interval'5 years'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

115020 rows affected.

       current_date   orderdate
0        2025-08-24  2020-08-24
1        2025-08-24  2020-08-24
2        2025-08-24  2020-08-24
3        2025-08-24  2020-08-24
4        2025-08-24  2020-08-24
...             ...         ...
115015   2025-08-24  2024-04-20
115016   2025-08-24  2024-04-20
115017   2025-08-24  2024-04-20
115018   2025-08-24  2024-04-20
115019   2025-08-24  2024-04-20

[115020 rows x 2 columns]

In [40]:
%%sql
select current_date,orderdate,
categoryname,
sum(exchangerate*netprice*quantity) as net_revenue
from sales s
join product p
on s.productkey=p.productkey
where orderdate>= current_date - interval'5 years'---more precise than extract - current in the previous code
group by orderdate,categoryname
order by orderdate,categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

9643 rows affected.

     current_date   orderdate                   categoryname  net_revenue
0      2025-08-24  2020-08-24                          Audio       266.40
1      2025-08-24  2020-08-24        Cameras and camcorders       1821.29
2      2025-08-24  2020-08-24                    Cell phones        86.12
3      2025-08-24  2020-08-24                      Computers     11373.14
4      2025-08-24  2020-08-24  Music, Movies and Audio Books       877.81
...           ...         ...                            ...          ...
9638   2025-08-24  2024-04-20                      Computers     58353.68
9639   2025-08-24  2024-04-20                 Games and Toys      1744.30
9640   2025-08-24  2024-04-20                Home Appliances      1562.04
9641   2025-08-24  2024-04-20  Music, Movies and Audio Books      4949.43
9642   2025-08-24  2024-04-20                   TV and Video      9841.91

[9643 rows x 4 columns]

In [41]:
%%sql
select orderdate,
deliverydate
From sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate deliverydate
0       2015-01-01   2015-01-01
1       2015-01-01   2015-01-01
2       2015-01-01   2015-01-01
3       2015-01-01   2015-01-01
4       2015-01-01   2015-01-01
...            ...          ...
199868  2024-04-20   2024-04-21
199869  2024-04-20   2024-04-21
199870  2024-04-20   2024-04-22
199871  2024-04-20   2024-04-22
199872  2024-04-20   2024-04-22

[199873 rows x 2 columns]

In [42]:
%%sql
select
age ('2024-01-14','2024-01-08' ) --this is a string os cannot subtract 5 years from it gotta convert to integer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

     age
0 6 days

In [43]:
%%sql
select
extract(day from age('2024-01-14','2024-01-08') )-5 --extract return integer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  ?column?
0        1

In [44]:
%%sql
select
date_part('year',orderdate) as order_year,
round(avg(extract(DAYS from age(deliverydate,orderdate))),2) as avg_processing_time,
cast(sum(exchangerate*netprice*quantity)as integer) as net_revenue
from sales
where orderdate>= current_date - interval'5 years'
group by order_year
order by order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

   order_year avg_processing_time  net_revenue
0     2020.00                1.04      1697493
1     2021.00                1.36     21357977
2     2022.00                1.62     44864557
3     2023.00                1.75     33108566
4     2024.00                1.67      8396527

In [45]:
%%sql
select
orderdate,orderkey,linenumber,
orderkey*10+linenumber as order_line_number,
(exchangerate*netprice*quantity) as net_revenue,
sum(exchangerate*netprice*quantity) over(partition by orderdate) as daily_net_revenue,
(exchangerate*netprice*quantity)*100/sum(exchangerate*netprice*quantity) over(partition by orderdate) as pct_daily_revenue
from sales
order by
  orderdate,
  pct_daily_revenue desc
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,orderkey,linenumber,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,1004,3,10043,2395.10,11640.80,20.58
1,2015-01-01,1006,1,10061,1552.32,11640.80,13.34
2,2015-01-01,1002,2,10022,1302.91,11640.80,11.19
3,2015-01-01,1002,0,10020,1146.75,11640.80,9.85
4,2015-01-01,1005,0,10050,975.16,11640.80,8.38
5,2015-01-01,1002,1,10021,950.25,11640.80,8.16
6,2015-01-01,1004,1,10041,578.52,11640.80,4.97
7,2015-01-01,1008,1,10081,574.05,11640.80,4.93
8,2015-01-01,1000,1,10001,423.28,11640.80,3.64
9,2015-01-01,1004,0,10040,263.11,11640.80,2.26

In [46]:
%%sql
SELECT *,
100 * net_revenue / daily_net_revenue AS pct_daily_revenue
FROM (
SELECT
orderdate,
orderkey * 10 + linenumber AS order_line_item, (quantity * netprice * exchangerate) AS net_revenue,
SUM(quantity * netprice * exchangerate) OVER(PARTITION BY orderdate) AS daily_net_revenue
FROM
sales
) AS revenue_by_day

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderdate,order_line_item,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10000,63.49,11640.80,0.55
1,2015-01-01,10001,423.28,11640.80,3.64
2,2015-01-01,10010,108.75,11640.80,0.93
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10021,950.25,11640.80,8.16
...,...,...,...,...,...
199868,2024-04-20,33980341,914.61,96879.43,0.94
199869,2024-04-20,33980342,150.18,96879.43,0.16
199870,2024-04-20,33980350,147.78,96879.43,0.15
199871,2024-04-20,33980351,2019.62,96879.43,2.08
199872,2024-04-20,33980352,56.83,96879.43,0.06

In [47]:
%%sql
with yearly_cohort as(
SELECT distinct customerkey,
extract(YEAR from min(orderdate) over(partition by customerkey)) as cohort_year
from sales
)
select y.cohort_year,
extract(year from orderdate) as purchase_year ,
SUM(quantity * netprice * exchangerate)as net_revenue
from sales s
left join yearly_cohort y on s.customerkey=y.customerkey
group by y.cohort_year,purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  net_revenue
0         2019          2022   4848980.74
1         2020          2020   7265759.44
2         2018          2022   4534295.81
3         2017          2018   1407065.13
4         2016          2022   2164681.10
5         2021          2021  12635597.87
6         2018          2024    936833.89
7         2018          2023   3271753.92
8         2023          2023  14345184.96
9         2020          2024    312983.02
10        2016          2018   1074607.29
11        2016          2024    364066.76
12        2017          2020    625928.03
13        2019          2020   1295044.99
14        2021          2023   2242369.63
15        2018          2020   1171126.65
16        2022          2022  24412138.13
17        2016          2016   9990990.20
18        2017          2021   1329858.72
19        2021          2022   3014082.50
20        2019          2024    751725.53
21        2016          2021    964417.85
22        2020          2023   1435051.04
23        2021          2024    495686.18
24        2015          2018   1069850.87
25        2015          2020    386489.60
26        2018          2019   3229188.22
27        2015          2022   1569787.72
28        2015          2021    872845.99
29        2016          2019   1565400.72
30        2016          2020    474087.09
31        2017          2024    464802.56
32        2019          2021   2337594.77
33        2022          2023   4237220.04
34        2018          2021   2201262.39
35        2018          2018  21115924.55
36        2017          2019   1764716.90
37        2024          2024   2856649.33
38        2020          2022   1891708.40
39        2019          2019  24022798.65
40        2020          2021   1016399.07
41        2015          2015   7370979.48
42        2017          2023   1714010.18
43        2015          2017    479841.31
44        2019          2023   3440099.20
45        2017          2022   2428882.80
46        2022          2024   1223450.12
47        2016          2023   1265242.63
48        2015          2016    392623.48
49        2015          2024    356186.62
50        2023          2024    634143.37
51        2016          2017    497028.11
52        2015          2019   1235991.48
53        2017          2017  12244469.63
54        2015          2023   1157633.91

In [48]:
%%sql
with yearly_cohort as(
select distinct customerkey,
extract(year from min(orderdate) over(partition by customerkey)) as cohort_year,
extract(year from orderdate) as purchase_year
from sales
)
select distinct cohort_year,
purchase_year,count(customerkey) over(partition by cohort_year,
purchase_year) as num_customers
from yearly_cohort
order by cohort_year,
purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  num_customers
0         2015          2015           2825
1         2015          2016            126
2         2015          2017            149
3         2015          2018            348
4         2015          2019            388
5         2015          2020            171
6         2015          2021            295
7         2015          2022            600
8         2015          2023            499
9         2015          2024            146
10        2016          2016           3397
11        2016          2017            174
12        2016          2018            374
13        2016          2019            457
14        2016          2020            205
15        2016          2021            336
16        2016          2022            746
17        2016          2023            573
18        2016          2024            183
19        2017          2017           4068
20        2017          2018            473
21        2017          2019            570
22        2017          2020            251
23        2017          2021            450
24        2017          2022            943
25        2017          2023            738
26        2017          2024            246
27        2018          2018           7446
28        2018          2019           1081
29        2018          2020            475
30        2018          2021            779
31        2018          2022           1644
32        2018          2023           1407
33        2018          2024            426
34        2019          2019           7755
35        2019          2020            523
36        2019          2021            873
37        2019          2022           1700
38        2019          2023           1439
39        2019          2024            370
40        2020          2020           3031
41        2020          2021            358
42        2020          2022            694
43        2020          2023            547
44        2020          2024            163
45        2021          2021           4663
46        2021          2022           1051
47        2021          2023            889
48        2021          2024            268
49        2022          2022           9010
50        2022          2023           1764
51        2022          2024            561
52        2023          2023           5890
53        2023          2024            332
54        2024          2024           1402

In [50]:
%%sql
with yearly_cohort as(
select customerkey,extract(year from min(orderdate)) as cohort_year,
sum(netprice*quantity*exchangerate) as customer_ltv
from sales
group by customerkey
)
select *,avg(customer_ltv) over(partition by cohort_year) as avg_cohort_ltv
from yearly_cohort
order by cohort_year,customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv  avg_cohort_ltv
0             4376        2015        182.00         5271.59
1             4403        2015       9530.35         5271.59
2             4925        2015       6078.08         5271.59
3             5729        2015        192.16         5271.59
4             6048        2015       1903.89         5271.59
...            ...         ...           ...             ...
49482      2093965        2024        475.22         2037.55
49483      2095129        2024        156.00         2037.55
49484      2095691        2024        326.00         2037.55
49485      2096470        2024        535.78         2037.55
49486      2097541        2024       1143.15         2037.55

[49487 rows x 4 columns]

In [51]:
%%sql
with cohort as(
select
    customerkey,
    extract(year from min(orderdate) over(partition by customerkey)) as cohort_year
from sales
)
select*
from cohort
where cohort_year >='2020'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

81370 rows affected.

       customerkey cohort_year
0               15        2021
1              406        2021
2              406        2021
3              545        2023
4              545        2023
...            ...         ...
81365      2099697        2022
81366      2099697        2022
81367      2099743        2022
81368      2099743        2022
81369      2099743        2022

[81370 rows x 2 columns]

In [52]:
%%sql
select customerkey,orderdate,(quantity*netprice*exchangerate) as net_revenue,
count(*) over(partition by customerkey order by orderdate) as running_order_count,
avg(quantity*netprice*exchangerate) over(partition by customerkey order by orderdate) as running_avg_revenue
from
  sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,orderdate,net_revenue,running_order_count,running_avg_revenue
0,15,2021-03-08,2217.41,1,2217.41
1,180,2018-07-28,525.31,1,525.31
2,180,2023-08-28,71.36,3,836.74
3,180,2023-08-28,1913.55,3,836.74
4,185,2019-06-01,1395.52,1,1395.52
...,...,...,...,...,...
199868,2099711,2016-08-13,2067.75,1,2067.75
199869,2099711,2017-08-14,3940.92,2,3004.34
199870,2099743,2022-03-17,375.57,2,234.81
199871,2099743,2022-03-17,94.05,2,234.81
199872,2099743,2023-02-11,598.46,3,356.03

In [53]:
%%sql
select row_number() over(partition by orderdate order by orderdate,orderkey,linenumber) as row_num,
*
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,row_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,2,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,3,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,4,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,5,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,93,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,94,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,95,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,96,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,97,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [54]:
%%sql
 select customerkey,count(*) as total_orders,
 row_number()over( order by count(*) desc ) as total_order_row_num,
 rank() over( order by count(*)desc ) as total_order_rank,
 dense_rank() over( order by count(*)desc ) as total_order_dense_rank
 from sales
 group by customerkey
 limit 15

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

15 rows affected.

,customerkey,total_orders,total_order_row_num,total_order_rank,total_order_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,459519,26,4,4,4
4,1495941,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,759419,24,8,8,6
8,1427444,24,9,8,6
9,1876222,24,10,8,6
10,2079681,22,11,11,7
11,578215,22,12,11,7
12,1743963,22,13,11,7
13,1780427,22,14,11,7
14,1496962,22,15,11,7

In [55]:
%%sql
with monthly_revenue as(
select
  to_char(orderdate,'yyyy-mm') AS order_month,
  sum(quantity*netprice*exchangerate) as net_revenue
from sales
where extract(year from orderdate)='2023'
--where orderdate between '2023-01-01' and '2023-12-31'
group by order_month
order by order_month
)
select*,
        first_value(net_revenue) over(order by order_month) as  first_month_revenue,
        last_value(net_revenue) over(order by order_month rows between unbounded preceding and unbounded following) as  last_month_revenue,
        nth_value(net_revenue,3) over(order by order_month rows between unbounded preceding and unbounded following) as  third_month_revenue
from monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,order_month,net_revenue,first_month_revenue,last_month_revenue,third_month_revenue
0,2023-01,3664431.34,3664431.34,2928550.93,2244316.52
1,2023-02,4465204.57,3664431.34,2928550.93,2244316.52
2,2023-03,2244316.52,3664431.34,2928550.93,2244316.52
3,2023-04,1162796.16,3664431.34,2928550.93,2244316.52
4,2023-05,2943005.99,3664431.34,2928550.93,2244316.52
5,2023-06,2864500.03,3664431.34,2928550.93,2244316.52
6,2023-07,2337639.34,3664431.34,2928550.93,2244316.52
7,2023-08,2623919.79,3664431.34,2928550.93,2244316.52
8,2023-09,2622774.85,3664431.34,2928550.93,2244316.52
9,2023-10,2551322.61,3664431.34,2928550.93,2244316.52
10,2023-11,2700103.38,3664431.34,2928550.93,2244316.52
11,2023-12,2928550.93,3664431.34,2928550.93,2244316.52

In [56]:
%%sql
with monthly_revenue as(
select
  to_char(orderdate,'yyyy-mm') AS order_month,
  sum(quantity*netprice*exchangerate) as net_revenue
from sales
where extract(year from orderdate)='2023'
--where orderdate between '2023-01-01' and '2023-12-31'
group by order_month
order by order_month
)
select*,
        lag(net_revenue) over(order by order_month) as  previous_month_revenue,
        lag(net_revenue,3) over(order by order_month) as  previous_month_revenue,--3 previous
        lead(net_revenue) over(order by order_month) as  next_month_revenue,
        lead(net_revenue,3) over(order by order_month) as  next3_month_revenue--3 month front
from monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,order_month,net_revenue,previous_month_revenue,previous_month_revenue,next_month_revenue,next3_month_revenue
0,2023-01,3664431.34,NaN,NaN,4465204.57,1162796.16
1,2023-02,4465204.57,3664431.34,NaN,2244316.52,2943005.99
2,2023-03,2244316.52,4465204.57,NaN,1162796.16,2864500.03
3,2023-04,1162796.16,2244316.52,3664431.34,2943005.99,2337639.34
4,2023-05,2943005.99,1162796.16,4465204.57,2864500.03,2623919.79
5,2023-06,2864500.03,2943005.99,2244316.52,2337639.34,2622774.85
6,2023-07,2337639.34,2864500.03,1162796.16,2623919.79,2551322.61
7,2023-08,2623919.79,2337639.34,2943005.99,2622774.85,2700103.38
8,2023-09,2622774.85,2623919.79,2864500.03,2551322.61,2928550.93
9,2023-10,2551322.61,2622774.85,2337639.34,2700103.38,NaN
10,2023-11,2700103.38,2551322.61,2623919.79,2928550.93,NaN
11,2023-12,2928550.93,2700103.38,2622774.85,NaN,NaN

In [57]:
%%sql
with monthly_revenue as(
select
  to_char(orderdate,'yyyy-mm') AS order_month,
  sum(quantity*netprice*exchangerate) as net_revenue
from sales
where extract(year from orderdate)='2023'
--where orderdate between '2023-01-01' and '2023-12-31'
group by order_month
order by order_month
)
select*,
        lag(net_revenue) over(order by order_month) as  previous_month_revenue,
        net_revenue-lag(net_revenue) over(order by order_month) as  month_rev_growth,--diff
        100*(net_revenue-lag(net_revenue) over(order by order_month))/lag(net_revenue) over(order by order_month) as  month_rev_growth_percent
from monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,order_month,net_revenue,previous_month_revenue,month_rev_growth,month_rev_growth_percent
0,2023-01,3664431.34,NaN,NaN,NaN
1,2023-02,4465204.57,3664431.34,800773.22,21.85
2,2023-03,2244316.52,4465204.57,-2220888.05,-49.74
3,2023-04,1162796.16,2244316.52,-1081520.36,-48.19
4,2023-05,2943005.99,1162796.16,1780209.83,153.10
5,2023-06,2864500.03,2943005.99,-78505.96,-2.67
6,2023-07,2337639.34,2864500.03,-526860.69,-18.39
7,2023-08,2623919.79,2337639.34,286280.45,12.25
8,2023-09,2622774.85,2623919.79,-1144.94,-0.04
9,2023-10,2551322.61,2622774.85,-71452.24,-2.72
10,2023-11,2700103.38,2551322.61,148780.78,5.83
11,2023-12,2928550.93,2700103.38,228447.54,8.46

In [60]:
%%sql
with monthly as(
select
extract(year from min(orderdate)) as cohort_year,
sum(quantity*netprice*exchangerate) as sum_lifetime
from sales
group by customerkey
),
avg_cohort as(
select cohort_year,avg(sum_lifetime)as avg_lifetime
from monthly
group by cohort_year
)
select *,
lag(avg_lifetime)over(order by cohort_year) as prev_avg_lifetime,
100*(avg_lifetime-lag(avg_lifetime)over(order by cohort_year))/lag(avg_lifetime)over(order by cohort_year)as percent_change,
lead(avg_lifetime)over(order by cohort_year) as lead_avg_lifetime
from avg_cohort
order by cohort_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,cohort_year,avg_lifetime,prev_avg_lifetime,percent_change,lead_avg_lifetime
0,2015,5271.59,NaN,NaN,5404.92
1,2016,5404.92,5271.59,2.53,5403.08
2,2017,5403.08,5404.92,-0.03,4896.64
3,2018,4896.64,5403.08,-9.37,4731.95
4,2019,4731.95,4896.64,-3.36,3933.32
5,2020,3933.32,4731.95,-16.88,3943.33
6,2021,3943.33,3933.32,0.25,3315.52
7,2022,3315.52,3943.33,-15.92,2543.18
8,2023,2543.18,3315.52,-23.29,2037.55
9,2024,2037.55,2543.18,-19.88,NaN

In [ ]:
%%sql
select customerkey, quantity*netprice,
       sum(quantity*netprice) over(partition by customerkey) as total_spent_per_customer
from sales;

In [81]:
%%sql
with monthly_sales as (
select
  to_char(orderdate,'yyyy-mm') as month,
  sum(quantity*netprice*exchangerate) as net_revenue
from sales
where extract(year from orderdate)=2023
group by month
order by month
)
select *,
      avg(net_revenue) over(order by month
      rows between current row and current row) as net_revenue_current
from monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           3664431.34
1   2023-02   4465204.57           4465204.57
2   2023-03   2244316.52           2244316.52
3   2023-04   1162796.16           1162796.16
4   2023-05   2943005.99           2943005.99
5   2023-06   2864500.03           2864500.03
6   2023-07   2337639.34           2337639.34
7   2023-08   2623919.79           2623919.79
8   2023-09   2622774.85           2622774.85
9   2023-10   2551322.61           2551322.61
10  2023-11   2700103.38           2700103.38
11  2023-12   2928550.93           2928550.93

In [83]:
%%sql
with monthly_sales as (
select
  to_char(orderdate,'yyyy-mm') as month,
  sum(quantity*netprice*exchangerate) as net_revenue
from sales
where extract(year from orderdate)=2023
group by month
order by month
)
select *,
      avg(net_revenue) over(order by month
      rows between 1 preceding and current row) as net_revenue_current
from monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           3664431.34
1   2023-02   4465204.57           4064817.96
2   2023-03   2244316.52           3354760.54
3   2023-04   1162796.16           1703556.34
4   2023-05   2943005.99           2052901.08
5   2023-06   2864500.03           2903753.01
6   2023-07   2337639.34           2601069.68
7   2023-08   2623919.79           2480779.57
8   2023-09   2622774.85           2623347.32
9   2023-10   2551322.61           2587048.73
10  2023-11   2700103.38           2625712.99
11  2023-12   2928550.93           2814327.15

In [85]:
 %%sql
with monthly_sales as (
select
  to_char(orderdate,'yyyy-mm') as month,
  sum(quantity*netprice*exchangerate) as net_revenue
from sales
where extract(year from orderdate)=2023
group by month
order by month
)
select *,
      avg(net_revenue) over(order by month
      rows between 1 preceding and 1 following) as net_revenue_current-- last,current and next month
from monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           4064817.96
1   2023-02   4465204.57           3354760.54
2   2023-03   2244316.52           1703556.34
3   2023-04   1162796.16           2052901.08
4   2023-05   2943005.99           2903753.01
5   2023-06   2864500.03           2601069.68
6   2023-07   2337639.34           2480779.57
7   2023-08   2623919.79           2623347.32
8   2023-09   2622774.85           2587048.73
9   2023-10   2551322.61           2625712.99
10  2023-11   2700103.38           2814327.15
11  2023-12   2928550.93           2928550.93

In [87]:
%%sql
with monthly_revenue as(
select
  to_char(orderdate,'yyyy-mm') AS order_month,
  sum(quantity*netprice*exchangerate) as net_revenue
from sales
where extract(year from orderdate)='2023'
--where orderdate between '2023-01-01' and '2023-12-31'
group by order_month
order by order_month
)
select*,
        first_value(net_revenue) over(order by order_month) as  first_month_revenue,
        last_value(net_revenue) over(order by order_month rows between unbounded preceding and unbounded following ) as  last_month_revenue,
        nth_value(net_revenue,3) over(order by order_month rows between unbounded preceding and unbounded following ) as  third_month_revenue
from monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,order_month,net_revenue,first_month_revenue,last_month_revenue,third_month_revenue
0,2023-01,3664431.34,3664431.34,2928550.93,NaN
1,2023-02,4465204.57,3664431.34,2928550.93,NaN
2,2023-03,2244316.52,3664431.34,2928550.93,2244316.52
3,2023-04,1162796.16,3664431.34,2928550.93,2244316.52
4,2023-05,2943005.99,3664431.34,2928550.93,2244316.52
5,2023-06,2864500.03,3664431.34,2928550.93,2244316.52
6,2023-07,2337639.34,3664431.34,2928550.93,2244316.52
7,2023-08,2623919.79,3664431.34,2928550.93,2244316.52
8,2023-09,2622774.85,3664431.34,2928550.93,2244316.52
9,2023-10,2551322.61,3664431.34,2928550.93,2244316.52
10,2023-11,2700103.38,3664431.34,2928550.93,2244316.52
11,2023-12,2928550.93,3664431.34,2928550.93,2244316.52