<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

select *
from sales
limit 100

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

100 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8000,2,2015-01-08,2015-01-08,591707,240,1045,1,940.80,903.17,311.71,EUR,0.85
96,8001,0,2015-01-08,2015-01-08,1963405,660,2014,2,149.99,139.49,68.98,USD,1.00
97,8001,1,2015-01-08,2015-01-08,1963405,660,1684,8,11.82,11.82,3.92,USD,1.00
98,8001,2,2015-01-08,2015-01-08,1963405,660,1314,2,328.00,295.20,150.83,USD,1.00
99,8001,3,2015-01-08,2015-01-08,1963405,660,1048,2,683.20,608.05,226.35,USD,1.00

In [4]:
%%sql

SELECT tablename
FROM pg_tables
WHERE schemaname = 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

          tablename
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [5]:
%%sql
select * from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [24]:
%%sql
select s.orderdate,
  s.netprice*s.quantity*s.exchangerate as net_revenue,c.givenname,c.surname,c.countryfull,c.continent,p.productkey,p.productname,p.categoryname,p.subcategoryname,
  case when s.netprice*s.quantity*s.exchangerate>1000 then 'high' else 'low' end as high_low
from
  sales s
left join customer c on s.customerkey=c.customerkey
left join product p on s.productkey=p.productkey

where orderdate::date >='2020-01-01'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-01,3075.80,David,Stone,United States,North America,1051,"A. Datum SLR Camera 35"" M358 Silver",Cameras and camcorders,Digital SLR Cameras,high
1,2020-01-01,444.34,David,Stone,United States,North America,1709,MGS Gears of War M170,Games and Toys,Download Games,low
2,2020-01-01,1187.73,David,Stone,United States,North America,457,WWI Desktop PC1.60 E1600 White,Computers,Desktops,high
3,2020-01-01,36.78,David,Stone,United States,North America,1385,Contoso Multi-line phones M30 Grey,Cell phones,Home & Office Phones,low
4,2020-01-01,4.45,David,Stone,United States,North America,1665,MGS Hand Games for 12-16 boys E600 Yellow,Games and Toys,Boxed Games,low
...,...,...,...,...,...,...,...,...,...,...,...
124446,2024-04-20,14.35,Guus,Doodeman,Netherlands,Europe,849,Contoso Ultraportable Neoprene Sleeve E30 Green,Computers,Computers Accessories,low
124447,2024-04-20,261.32,Guus,Doodeman,Netherlands,Europe,1651,Contoso DVD 9-Inch Player Portable M300 Silver,"Music, Movies and Audio Books",Movie DVD,low
124448,2024-04-20,147.78,Michael,Wilson,Canada,North America,1575,SV DVD Player M140 Gold,"Music, Movies and Audio Books",Movie DVD,low
124449,2024-04-20,2019.62,Michael,Wilson,Canada,North America,415,Proseware Laptop8.9 E089 White,Computers,Laptops,high
124450,2024-04-20,56.83,Michael,Wilson,Canada,North America,1693,SV Hand Games men M30 Black,Games and Toys,Boxed Games,low

Warning: total number of rows (124451) exceeds max_rows (20000). Limiting to first (20000) rows.